version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME: "docker-info:username"
    SECRET_PASSWORD: "docker-info:password"
phases:
  pre_build:
    commands:
      - echo "Logging into docker hub"
      - echo "$SECRET_PASSWORD" | docker login -u $SECRET_USERNAME --password-stdin
  build:
    commands:
      - echo "Building docker image..."
      - docker build -t nicholaseldergill/pottery-db:latest .
  post_build:
    -commands:
      - echo "Pushing docker image"
      - docker push nicholaseldergill/pottery-db:latest
artifacts: 
  files:
    - Dockerfile